import { test, expect } from '@playwright/test';

let createdFilePath = '';

test('create, save and delete markdown file', async ({ page, request }) =>
{
    await page.goto('http://localhost:3100');
    await page.getByLabel('Category:').selectOption({ index: 0 });
    await page.getByLabel('Title:').fill('Test with Playwright');
    await page.getByText('🛠️ Generate File Path').click();

    createdFilePath = await page.locator('#markdown-path').inputValue();
    await page.getByLabel('Description:').fill('Generated by Playwright');
    await page.locator('#editor textarea').fill('# Hello Playwright');
    await page.getByText('Save').click();
    await expect(page.locator('#status-message')).toHaveText('Saved!');

    const res = await request.delete(`http://localhost:3100/api/delete-markdown?path=${encodeURIComponent(createdFilePath)}`);
    expect(res.status()).toBe(200);
});